### ISSUE TITLE
Error waiting for a debug connection: The log reader stopped unexpectedly, or never started.

### ISSUE THREAD

**Issue by YowFung** [bitsdojo/bitsdojo_window#157]
A duplication of https://github.com/flutter/flutter/issues/101168 .

**Comment by namangor04** [comment]
Same here! Did anyone find a solution?

**Comment by namangor04** [comment]
> I'm using Windows 11 and it doesn't happens on Win 10.

Which win 11 build @joaovperin ?

**Comment by joaovperin** [comment]
> > I'm using Windows 11 and it doesn't happens on Win 10.
> 
> Which win 11 build @joaovperin ?

Well, I keep the system always updated, so I tried in a lot, but can't retrieve now because it has passed some time. 
But I found a workaround.

The bug was happening because of these lines on main.c : 

```
#include <bitsdojo_window_windows/bitsdojo_window_plugin.h>
auto bdw = bitsdojo_window_configure(BDW_CUSTOM_FRAME | BDW_HIDE_ON_STARTUP);
```

I just removed them and implemented some manual workaround. At win32_window.cpp, set these flags:

```WS_POPUP | WS_THICKFRAME``` (in place of the default ```WS_OVERLAPPEDWINDOW | WS_VISIBLE``` at the ```HWND window = CreateWindow(...)``` call.

And don't forget to set window visible at main.dart, just after calling runApp:

```dart
 // Configure the main Window
  AppWindow.doWhenWindowReady(() {
    appWindow.size = const Size(1280, 720.0);
    appWindow.minSize = const Size(500, 720.0);
    appWindow.title = 'Your Title';
    appWindow.alignment = Alignment.center;
    appWindow.show();
  });
```

I think it should do the trick for you. But I strongly recommend you to stop using this lib, as long as it looks no longer being actively mantained.

**Comment by namangor04** [comment]
Okay great! Thank you @joaovperin, which lib did you migrate to then? I don't think there are any alternatives as of now.

**Comment by namangor04** [comment]
Okay great! Thank you very much @joaovperin , I really appreciate your help! Which lib did you migrate to then? I don't think there are any alternatives as of now for flutter other than self implementing such a package.

**Comment by bitsdojo** [comment]
@namangor04 I have been away in the last months taking care of a health problem that kept me from doing any significant work.

I have lots of changes on the private branch that I need to merge to the public branch and you will see more of those in the next weeks.

**Comment by namangor04** [comment]
@bitsdojo I'm so sorry to hear about that, Take Rest and Get Well Soon 💐. Thank you for this amazing package though! We have been using it since about a year or so and it has worked great! This is the only issue we have faced. No problem though, please take good care of your health, Thank you for the prompt reply!

**Comment by namangor04** [comment]
> I decided to keep using this until I have time to implement my own code, because I want to support some Windows 7 users.

You can check out [this](https://github.com/bitsdojo/bitsdojo_window/pull/100) PR as it adds support for Windows 7 and early windows 10. 

And [this](https://github.com/bitsdojo/bitsdojo_window/pull/134) PR fixes the current issue!

**Comment by twa-software** [comment]
Hey @bitsdojo, any progress here? The issue was completed, but the PRs weren't merged yet.

#134 fix this issue, please merge it a.s.a.p!
And #100 would be great also.

If you need some help to maintain this lib, let us know. But please, don't let the project die.

**Comment by joaovperin** [comment]
Hey @bitsdojo, any progress here? The issue was completed, but the PRs weren't merged yet.

https://github.com/bitsdojo/bitsdojo_window/pull/134 fix this issue, please merge it a.s.a.p!
And https://github.com/bitsdojo/bitsdojo_window/pull/100 would be great also.

If you need some help to maintain this lib, let us know. But please, don't let the project die.

**Comment by namangor04** [comment]
@bitsdojo please merge #134 and #100 as soon as possible. They fix critical issues which are affecting us!

**Comment by namangor04** [comment]
Please merge #197 so that this issue can be closed @bitsdojo . Thank you! :)

**Comment by bitsdojo** [comment]
> @bitsdojo please merge #134 and #100 as soon as possible. They fix critical issues which are affecting us!

I hear you. Just pushed 0.1.5. Feel free to re-open if you encounter any issues.

**Comment by namangor04** [comment]
Thank you very much mate! :)

**Comment by martemorfosis** [comment]
Hello @bitsdojo.

I still had to make the manual changes that @joaovperin suggested in order to make my app work on Windows 11 (it was showing just a blank window. On Windows 10 it was working fine tho.) 

BTW I'm using version 0.1.15 of the plugin.

**Comment by bitsdojo** [comment]
Thank you for reporting. I will try it on my side and see what I can do about it.
