### ISSUE TITLE
Upgrade to win^5.0.6

### ISSUE THREAD

**Issue by victor7w7r** [bitsdojo/bitsdojo_window#224]
Its an emergency, please please 😢 😢

**Comment by hsangtini** [comment]
please upgrade dev @bitsdojo

**Comment by JHenneberg** [comment]
It is solved in #216 but not merged yet.

**Comment by prinkeeras** [comment]
is this package still being maintained?

**Comment by JHenneberg** [comment]
last comment was https://github.com/bitsdojo/bitsdojo_window/issues/220#issuecomment-1637078244

**Comment by ANC1024GO** [comment]
Resolving dependencies...
Because bitsdojo_window >=0.1.5 depends on bitsdojo_window_windows ^0.1.5 which depends on win32 ^3.0.0, bitsdojo_window >=0.1.5 requires win32 ^3.0.0.
And because wakelock_plus 1.1.1 depends on win32 >=4.0.0 <6.0.0 and no versions of wakelock_plus match >1.1.1 <2.0.0, bitsdojo_window >=0.1.5 is incompatible with wakelock_plus ^1.1.1.
And because media_kit_video 1.1.5 depends on wakelock_plus ^1.1.1 and no versions of media_kit_video match >1.1.5 <2.0.0, bitsdojo_window >=0.1.5 is incompatible with media_kit_video ^1.1.5.
So, because sinzar_tv depends on both media_kit_video ^1.1.5 and bitsdojo_window ^0.1.5, version solving failed.
exit code 1

**Comment by PassionPenguin** [comment]
+1

**Comment by bitsdojo** [comment]
Please try updating to the latest `bitsdojo_window` version.
