### ISSUE TITLE
solution for this please

### ISSUE THREAD

**Issue by renejk** [bitsdojo/bitsdojo_window#30]
[bodega] flutter pub get
Running "flutter pub get" in bodega...                          
    Because bitsdojo_window >=0.0.6 depends on bitsdojo_window_windows ^0.0.2 which depends on win32 ^2.0.0, bitsdojo_window >=0.0.6 requires win32 ^2.0.0.

(1) So, because shared_preferences_windows <0.0.3-nullsafety depends on path_provider_windows ^0.0.2 which depends on win32 ^1.7.1, bitsdojo_window >=0.0.6 is incompatible with shared_preferences_windows <0.0.3-nullsafety.

    Because shared_preferences_windows >=0.0.3-nullsafety <2.0.0 depends on shared_preferences_platform_interface ^2.0.0-nullsafety and shared_preferences 0.5.12+4 depends on shared_preferences_platform_interface ^1.0.0, shared_preferences_windows >=0.0.3-nullsafety <2.0.0 is incompatible with shared_preferences 0.5.12+4.

    And because shared_preferences 0.5.12+4 depends on shared_preferences_windows ^0.0.1, shared_preferences 0.5.12+4 requires shared_preferences_windows >=0.0.1 <0.0.3-nullsafety.

    And because bitsdojo_window >=0.0.6 is incompatible with shared_preferences_windows <0.0.3-nullsafety (1), bitsdojo_window >=0.0.6 is incompatible with shared_preferences 0.5.12+4.

    And because no versions of shared_preferences match >0.5.12+4 <0.6.0, bitsdojo_window >=0.0.6 is incompatible with shared_preferences ^0.5.12+4.

    So, because bodega_flutter depends on both shared_preferences ^0.5.12+4 and bitsdojo_window ^0.0.6, version solving failed.
pub get failed (1;     So, because bodega_flutter depends on both shared_preferences ^0.5.12+4 and bitsdojo_window ^0.0.6, version solving failed.)
exit code 1

**Comment by bitsdojo** [comment]
Try upgrading shared_preferences plugin to a newer version.

**Comment by bitsdojo** [comment]
Can you try upgrading shared_preferences to the latest version and let me know how that goes?

**Comment by esDotDev** [comment]
We're also having this issue. Upgrading shared_preferences to any of the 2.0.0 versions, seems to just set off more cascades of errors. 

* it then goes on to compain about `path_provider` so I up that to 2.0, 
* which then leads to some complaint about `xdg_directories`, so we up that to 0.2.0, 
* then goes to `cached_network_image` blowing up. 
`Because no versions of cached_network_image match >2.5.0 and cached_network_image >=0.4.0-rc.1 <0.4.0 depends on flutter_cache_manager ^0.1.0-rc.1, cached_network_image >=0.4.0-rc.1 <0.4.0 or >2.5.0 requires flutter_cache_manager ^0.1.0-rc.1.`

This seems to end eventually in some sort of deadlock where cached_network_image  needs `path_provider: ^1.6.18` but all the others want `path_provider: ^2.0.0`.

Removing cached_network_image image, and everything actually builds!! Still not sure really what that was all about... I guess you upped your shared_prefs version which led to all of these down-stream upgrades required?

**Comment by Ali-Fadaei** [comment]
same here!

**Comment by Ali-Fadaei** [comment]
> [bodega] flutter pub get
> Running "flutter pub get" in bodega...
> Because bitsdojo_window >=0.0.6 depends on bitsdojo_window_windows ^0.0.2 which depends on win32 ^2.0.0, bitsdojo_window >=0.0.6 requires win32 ^2.0.0.
> 
> (1) So, because shared_preferences_windows <0.0.3-nullsafety depends on path_provider_windows ^0.0.2 which depends on win32 ^1.7.1, bitsdojo_window >=0.0.6 is incompatible with shared_preferences_windows <0.0.3-nullsafety.
> 
> ```
> Because shared_preferences_windows >=0.0.3-nullsafety <2.0.0 depends on shared_preferences_platform_interface ^2.0.0-nullsafety and shared_preferences 0.5.12+4 depends on shared_preferences_platform_interface ^1.0.0, shared_preferences_windows >=0.0.3-nullsafety <2.0.0 is incompatible with shared_preferences 0.5.12+4.
> 
> And because shared_preferences 0.5.12+4 depends on shared_preferences_windows ^0.0.1, shared_preferences 0.5.12+4 requires shared_preferences_windows >=0.0.1 <0.0.3-nullsafety.
> 
> And because bitsdojo_window >=0.0.6 is incompatible with shared_preferences_windows <0.0.3-nullsafety (1), bitsdojo_window >=0.0.6 is incompatible with shared_preferences 0.5.12+4.
> 
> And because no versions of shared_preferences match >0.5.12+4 <0.6.0, bitsdojo_window >=0.0.6 is incompatible with shared_preferences ^0.5.12+4.
> 
> So, because bodega_flutter depends on both shared_preferences ^0.5.12+4 and bitsdojo_window ^0.0.6, version solving failed.
> ```
> 
> pub get failed (1; So, because bodega_flutter depends on both shared_preferences ^0.5.12+4 and bitsdojo_window ^0.0.6, version solving failed.)
> exit code 1

Problem Solved with Flutter v2.0.0 ✔
